### ISSUE TITLE
Admin backend: can't change permalink in edit post

### ISSUE THREAD

**Issue by batlab** [batlab/trensmissions#24]
Reproduire : changer l'url, cliquer sur mettre à jour... l'url reprend sa valeur par défaut.

**Comment by leodh** [comment]
J'ai déjà eu ce problème plein de fois sur divers blogs, y compris sur l'ancien WP de TrENSmissions, c'est pas lié à ce qu'on fait. Je sais pas à quoi c'est dû.

**Comment by batlab** [comment]
C'est chelou parce qu'on l'avait pas sur l'ancien site en fait.

**Comment by leodh** [comment]
Au temps pour moi : https://wordpress.org/support/topic/cant-change-the-permalink-after-the-post-is-published
Par contre, du coup ça affiche une metabox moche avec le slug du post. La cacher en JS ?

**Comment by batlab** [comment]
Si c'est vraiment trop moche, on pourra la restyler via CSS. Je pense que ça devrait le faire.
