### ISSUE TITLE
Category doesn't save/show when validation fails

### ISSUE THREAD

**Issue by leodh** [batlab/trensmissions#31]
Create new post, chose a category (emission), other fields, but make sure not to be valid. Publish: it fails, and the category selector is back to "Choisissez une catégorie".

**Comment by leodh** [comment]
edit-post-form.php: line 80: $post_category_id = ( $post_category == 1 || $post_category == 0 ) ? $post_category[0]->cat_ID : (-1)
Must become:
 $post_category_id = (!( $post_category == 1 || $post_category == 0 )) ? $post_category[0]->cat_ID : (-1)

**Comment by batlab** [comment]
Tu sais que tu peux mettre des balises codes en markdown ^^ ?
```
$post_category_id = (!( $post_category == 1 || $post_category == 0 )) ? $post_category[0]->cat_ID : (-1)
```
